environment:
    matrix:
        - PYTHON: "C:\\Python27"
          PYTHON_VERSION: "2.7.x"
          PYTHON_ARCH: "32"

install:
    - pip install coveralls
    - pip install pathlib
    - pip install unittest2

test_script:
    - coverage run -m unittest2 discover

after_test:
    - coveralls
