language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install coveralls
    - pip install pathlib
    - pip install unittest2
script:
    - pushd test && coverage run -m unittest2 discover && popd
after_success:
    - pushd test && coveralls && popd
