language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install coveralls
    - pip install pathlib
    - pip install unittest2
script:
    - coverage run -m unittest2 discover
after_success:
    - coveralls
