language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install coveralls
- pip install pathlib
- pip install unittest2
script:
- coverage run -m unittest2 discover
after_success:
- coveralls
deploy:
  provider: pypi
  user: oneup40
  password:
    secure: swVJknlHZh7hi5hVH7sCz4OVlXBD1yOPCyMSK6OdinXYRXj5IjZ0M0W4LxDC+rhf5GigeOPy03+ln78ScwwbgCl7HdQ39VBvAKRPd7vK/Q0/oTygifW1LUZDAe4YwWK/R5PdhHNm9mWYz9Sx1lX+GhjexW8DiTplLKMxKbFP+HT8uc+Il4TS1VhBWD6FDTmz4Mf1qQsRA5JCxVghRqIEBV/U3Z9m7R8NHfGpjeGrOYlQfVYyJCj4EuAK43oiWSAIjSxCVccmPDDHd/oQprxGAbqVikJzXyoNrUxSlOOUGvJgqURp7YQNQ2vXvddsslfF33SGWq0p1HeQEdIh+SYzt6yOnk0nch3DBXpQm2w/dKAx4/0LamyA0PZdC+/k/LucCrGTxY5kjQ/Re4kXU4B1tnR1TBvq3ts3qr9YHBnGavnx4PIhqQb1nVuozDVoc0shGuJb3ut3a7XpKUZ7KUxoRlRR00jSbKE2EZbBj7/GO1DsTSg1yVO5WdHK9hElkiCbSstIN9Fa7XBI3qbzj60DCdg0UFlwjBgvC835kaQauIOv3M+Xp8tboIDDK0dHM8M0RKvTmpmz91sNzS3atEq5+vcjmR5Njg06sTK8HQpwKiESBQ+0IbfeSfVUtT9MVzX03yYROeL/Y/LwZluWEuTbMTjmXmkQ5Q60S85ikpTNW2I=
  on:
    tags: true
  distributions: sdist bdist_wheel
