language: python
python:
    - "2.7"
install:
    - pip install coveralls
    - pip install pathlib
script:
    - pushd test && coverage run -m unittest discover && popd
after_success:
    - pushd test && coveralls && popd
